---
language: python
python: "2.7"
before_install:
  - sudo apt-get install -qq python-apt python-pycurl

#sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook -i tests/inventory tests/test.yml
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --become -vvvv

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
