---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: test -e /usr/bin/python || (sudo apt-get -y install python-simplejson)
      register: output
      changed_when: output.stdout != ""
    - debug: var=docker_gpg_key_url
    - debug: var=docker_ce_apt_repo_url
    - debug: var=docker_cs_apt_repo_url
    - name: 'run setup'
      setup:
  roles:
    - role: ansible-role-docker
