---
- name: download docker-compose
  get_url:
    url: "{{ docker_compose_repo_url }}"
    dest: "{{docker_compose_bin_path}}/docker-compose"
    mode: a+x
  become: true
  tags:
    - 'docker'
    - 'docker-compose'
